### ISSUE TITLE
LD_LIBRARY_PATH causes issue with Nix

### ISSUE THREAD

**Issue by fenglengshun** [PikaOS-Linux/pkg-pika-baseos#1]
I got the following output when trying to update my home-manager build:

```
❯ home-manager switch -b bak
nix: error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument
nix: error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument
nix: error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument
```

Asking around the NixOS Discord, this seems to be because of LD_LIBRARY_PATH being set. Apparently [`/etc/profile.d/00-append-pika-ld.sh`](https://github.com/PikaOS-Linux/pkg-pika-baseos/blob/main/pika-baseos/etc/profile.d/00-append-pika-ld.sh) sets LD_LIBRARY_PATH into the following:

```
❯ echo $LD_LIBRARY_PATH
:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/local/lib/i386-linux-gnu:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib/i686-linux-gnu:/lib/i686-linux-gnu:/usr/lib/i686-linux-gnu:/usr/lib/x86_64-linux-gnu/libfakeroot-e:/opt/ffmpeg5/usr/lib/x86_64-linux-gnu:/opt/ffmpeg5/usr/lib/i386-linux-gnu-e::/opt/rocm/lib:/opt/rocm/lib64:/opt/rocm/profiler/lib:/opt/rocm/profiler/lib64:/opt/rocm/opencl/lib:/opt/rocm/hip/lib:/opt/rocm/opencl/lib64:/opt/rocm/hip/lib64:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/local/lib/i386-linux-gnu:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib/i686-linux-gnu:/lib/i686-linux-gnu:/usr/lib/i686-linux-gnu:/usr/lib/x86_64-linux-gnu/libfakeroot:/opt/ffmpeg5/usr/lib/x86_64-linux-gnu:/opt/ffmpeg5/usr/lib/i386-linux-gnu::/opt/rocm/lib:/opt/rocm/lib64:/opt/rocm/profiler/lib:/opt/rocm/profiler/lib64:/opt/rocm/opencl/lib:/opt/rocm/hip/lib:/opt/rocm/opencl/lib64:/opt/rocm/hip/lib64
```

Doing `unset LD_LIBRARY_PATH` allows me to run `home-manager switch` again, so that seems to be the issue. For now, I could just remove the `00-append-pika-ld.sh` for myself, but I don't know why that was set or if it'll cause issues.

**Comment by ToasterUwU** [comment]
Hey, not to shut you down or anything.. But this doesn't seem like an issue at all.

PikaOS is PikaOS, not NixOS. And I know you can use Nix outside of NixOS, and it's perfectly valid for some people.
But quite frankly, we don't actively support that use case, and I don't see why we would when we already have our own systems in place like Pikman.

If you want to use something else then we ship and tell people to use, you can do so, but don't expect us to fix issues you have from that.

**Comment by fenglengshun** [comment]
That's fair - although it was a surprise since recall `apx` was part of pika-os and they have Nix there (and the Vanilla team in general are pretty positive about it).

Is there some FAQ or Known Issues section, however? Nix is growing in terms of popularity, so just having it in Known Issues would help. At the very least, my intent in opening this issue is so that, if people are having the same issue and went to google, they may find this and can fix it themselves. 

Officially not supporting Nix is a fair stance, but making sure people are informed would simply be helpful, in my opinion.

**Comment by ToasterUwU** [comment]
You are the first one to have this issue and make it known.

So no, there is nothing I can link you that would help.

**Comment by ToasterUwU** [comment]
You can however add the unset command to your bashrc or equivalent. That way every session would automatically unset the env var that breaks Nix
